### ISSUE TITLE
Document existing/missing features

### ISSUE THREAD

**Issue by nmrshll** [fpgaminer/preserve#2]
Hi there, I want to jump in and contribute to this and/or rdedup.

What are the features that are already working here ? What features are essential that you haven't added yet ? Is this in a usable state already ?

Thanks in advance !

**Comment by fpgaminer** [comment]
Hey, I think it's really cool that you've taken an interest in this project.  To be honest though, right now it's just a hobby project that I'm building for my own needs.  So I don't have any time allocated to it that would allow me to get it ready for other's contributions.  Sorry :(

**Comment by nmrshll** [comment]
No worries ! I can always just fork it and have a look at the code.
Thanks for the reply !
